name: Release

on:
  push:
    tags:
      - 'v*'  # Run on tags like v1.0.0

jobs:
  release:
    name: Build & Upload Binaries
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to create releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Go binary
        run: |
          mkdir -p dist
          go build -o dist/hello_go go/hello.go -gccgoflags=-static

      - name: Build C++ binary (Alpine static)
        run: |
          docker run --rm \
            -v "$PWD":/src \
            -w /src/go \
            alpine:latest \
            sh -c "apk add --no-cache g++ musl-dev make && make && cp hello /srv/dist/hello-go"

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/hello-go
            dist/hello-cpp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

