name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # Run on tags like v1.0.0

jobs:
  release:
    name: Build & Upload Binaries
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to create releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
            
      - name: Prepare
        run: |
          mkdir -p dist/linux-bin

      - name: Build Go binary
        run: |
          go build -gccgoflags=-static -o dist/linux-bin/hello_go go/hello.go

      - name: Build C++ binary (Alpine static)
        run: |
          docker run --rm \
            -v "$PWD":/src \
            -w /src/cpp \
            alpine:latest \
            sh -c "apk add --no-cache g++ musl-dev make && make"
          cp cpp/hello dist/linux-bin/hello_cpp

      - name: Create add-on package
        run: |
         cd dist 
         cd tar -cvzf ../hello.taz *
         cd ..
         sha256sum hello.taz | cut -f1 -d" " > checksum.txt

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            hello.taz
            checksum.txt 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

